import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBell,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleDashed,
  IconCircleDot,
  IconCircleHalf2,
  IconCircleOff,
  IconCircleX,
  IconClock,
  IconCopy,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFilter,
  IconFolder,
  IconHeart,
  IconHelpCircle,
  IconHome,
  IconHourglassHigh,
  IconInfoCircle,
  IconLayoutGrid,
  IconList,
  IconLock,
  IconLockOpen,
  IconMail,
  IconMenu2,
  IconMinus,
  IconPhone,
  IconPlus,
  IconPrinter,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconShare,
  IconSortAscending,
  IconStar,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconX,
} from "@tabler/icons-react";
import type { ComponentProps } from "react";

/**
 * Registry of the 50 most commonly used Tabler icons, keyed by a stable,
 * kebab-case name.
 *
 * Components that accept an icon (for example {@link "../Button/Button"})
 * reference icons by these names rather than importing icon components
 * directly, so consumers never need to depend on `@tabler/icons-react`
 * themselves.
 */
export const iconRegistry = {
  home: IconHome,
  "hourglass-high": IconHourglassHigh,
  search: IconSearch,
  settings: IconSettings,
  user: IconUser,
  users: IconUsers,
  menu: IconMenu2,
  close: IconX,
  check: IconCheck,
  "chevron-down": IconChevronDown,
  "chevron-up": IconChevronUp,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  "arrow-left": IconArrowLeft,
  "arrow-right": IconArrowRight,
  "arrow-up": IconArrowUp,
  "arrow-down": IconArrowDown,
  plus: IconPlus,
  minus: IconMinus,
  trash: IconTrash,
  edit: IconEdit,
  download: IconDownload,
  upload: IconUpload,
  star: IconStar,
  heart: IconHeart,
  bell: IconBell,
  mail: IconMail,
  phone: IconPhone,
  calendar: IconCalendar,
  clock: IconClock,
  lock: IconLock,
  "lock-open": IconLockOpen,
  eye: IconEye,
  "eye-off": IconEyeOff,
  filter: IconFilter,
  "sort-ascending": IconSortAscending,
  refresh: IconRefresh,
  share: IconShare,
  copy: IconCopy,
  "external-link": IconExternalLink,
  "info-circle": IconInfoCircle,
  "alert-circle": IconAlertCircle,
  "alert-triangle": IconAlertTriangle,
  "help-circle": IconHelpCircle,
  "circle-check": IconCircleCheck,
  "circle-x": IconCircleX,
  "circle-dashed": IconCircleDashed,
  "circle-half-2": IconCircleHalf2,
  "circle-off": IconCircleOff,
  "circle-dot": IconCircleDot,
  list: IconList,
  "layout-grid": IconLayoutGrid,
  folder: IconFolder,
  file: IconFile,
  printer: IconPrinter,
} as const;

/** Names of every icon available in {@link iconRegistry}. */
export type IconName = keyof typeof iconRegistry;

/** Component type shared by every icon in {@link iconRegistry}. */
export type TablerIconComponent = (typeof iconRegistry)[IconName];

/** Props accepted by any Tabler icon component in {@link iconRegistry}. */
export type TablerIconProps = ComponentProps<TablerIconComponent>;

/** All icon names available in {@link iconRegistry}, for iteration. */
export const iconNames = Object.keys(iconRegistry) as IconName[];

/**
 * Re-exports of every Tabler icon component backing {@link iconRegistry},
 * for consumers who prefer to import an icon component directly instead of
 * going through `<Icon name="..." />`.
 */
export {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBell,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleDashed,
  IconCircleDot,
  IconCircleHalf2,
  IconCircleOff,
  IconCircleX,
  IconClock,
  IconCopy,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFilter,
  IconFolder,
  IconHeart,
  IconHelpCircle,
  IconHome,
  IconHourglassHigh,
  IconInfoCircle,
  IconLayoutGrid,
  IconList,
  IconLock,
  IconLockOpen,
  IconMail,
  IconMenu2,
  IconMinus,
  IconPhone,
  IconPlus,
  IconPrinter,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconShare,
  IconSortAscending,
  IconStar,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconX,
} from "@tabler/icons-react";
